spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springTutorial?createDatabaseIfNotExist=true&useSSL=true
    password: root
  jpa:
    generate-ddl: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: spring-tutorial
welcome:
  message: Hi Kalana
server:
  port: '8085'

